# Generated by Django 5.1.1 on 2024-10-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adress",
            name="zip",
            field=models.IntegerField(null=True),
        ),
    ]
