# Generated by Django 5.1.1 on 2024-12-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="Product",
            new_name="product",
        ),
    ]
